openapi: 3.0.1
info:
  title: Xero-OpenAPI
  description: "[Product] An OpenAPI (Swagger) specification for the Xero API with\
    \ OAuth 2.0 security schema."
  x-cortex-tag: xv95yce9FxfyArQM7Q3grV
  x-cortex-type: domain
  x-cortex-slack:
    channels:
    - name: help-xero-openapi-github
  x-cortex-groups:
  - domain-type:product
  - phase:sustained-release
  x-cortex-oncall:
    pagerduty:
      id: null
      type: SERVICE
  x-cortex-owners:
  - type: EMAIL
    email: null
    inheritance: APPEND