openapi: 3.0.0
servers:
  - description: Xero Payroll AU API
    url: https://api.xero.com/payroll.xro/1.0/
info:
  version: '1.0.0'
  title: 'Xero Payroll AU'
  description: 'This is the Xero Payroll API for orgs in Australia region.'
  termsOfService: "https://developer.xero.com/xero-developer-platform-terms-conditions/"
  contact:
    name: "Xero Platform Team"
    email: "api@xero.com"
    url: "https://developer.xero.com"
tags:
  - name: PayrollAU
    description: Operations available to regular developers
paths:
  /Employees:
    get:
      security:
        - OAuth2: [payroll.employees.read]
      tags:
        - PayrollAU
      operationId: getEmployees
      summary: searches employees
    post:
      security:
        - OAuth2: [payroll.employees]
      tags:
        - PayrollAU
      summary: Use this method to create a payroll employee
      operationId: createEmployee
  /Employees/{EmployeeId}:
    get:
      security:
        - OAuth2: [payroll.employees.read]
      tags:
        - PayrollAU
      summary: searches for an employee by unique id
      operationId: getEmployee
    post:
      security:
        - OAuth2: [payroll.employees]
      tags:
        - PayrollAU
      summary: Update an Employee 
      operationId: updateEmployee
      description:  Update properties on a single employee
  /LeaveApplications:
    get:
      security:
        - OAuth2: [payroll.leaveapplications.read]
      tags:
        - PayrollAU
      operationId: getLeaveApplications
      summary: searches Leave Applications
    post:
      security:
        - OAuth2: [payroll.leaveapplications]
      tags:
        - PayrollAU
      summary: Use this method to create a Leave Application
      operationId: createLeaveApplication
  /LeaveApplications/{LeaveApplicationId}:
    get:
      security:
        - OAuth2: [payroll.leaveapplications.read]
      tags:
        - PayrollAU
      summary: searches for an Leave Application by unique id
      operationId: getLeaveApplication
    post:
      security:
        - OAuth2: [payroll.leaveapplications]
      tags:
        - PayrollAU
      summary: Use this method to update a Leave Application
      operationId: updateLeaveApplication
  /PayItems:
    get:
      security:
        - OAuth2: [payroll.payitems.read]
      tags:
        - PayrollAU
      operationId: getPayItems
      summary: searches Pay Items
    post:
      security:
        - OAuth2: [payroll.payitems]
      tags:
        - PayrollAU
      summary: Use this method to create a Pay Item
      operationId: createPayItem
  /PayrollCalendars:
    get:
      security:
        - OAuth2: [payroll.payrollcalendars.read]
      tags:
        - PayrollAU
      operationId: getPayrollCalendars
      summary: searches Payroll Calendars
    post:
      security:
        - OAuth2: [payroll.payrollcalendars]
      tags:
        - PayrollAU
      summary: Use this method to create a Payroll Calendars
      operationId: createPayrollCalendar
  /PayrollCalendars/{PayrollCalendarID}:
    get:
      security:
        - OAuth2: [payroll.payrollcalendars.read]
      tags:
        - PayrollAU
      operationId: getPayrollCalendar
      summary: searches Payroll Calendars
  /PayRuns:
    get:
      security:
        - OAuth2: [payroll.payruns.read]
      tags:
        - PayrollAU
      operationId: getPayRuns
      summary: searches PayRuns
    post:
      security:
        - OAuth2: [payroll.payruns]
      tags:
        - PayrollAU
      summary: Use this method to create a PayRun
      operationId: createPayRun
  /PayRun/{PayRunID}:
    get:
      security:
        - OAuth2: [payroll.payruns.read]
      tags:
        - PayrollAU
      summary: searches for an payrun by unique id
      operationId: getPayRun
    post:
      security:
        - OAuth2: [payroll.payruns]
      tags:
        - PayrollAU
      summary: Update a PayRun 
      operationId: updatePayRun
      description:  Update properties on a single PayRun
  /Payslip:
    post:
      security:
        - OAuth2: [payroll.payslip]
      tags:
        - PayrollAU
      summary: Use this add, update or delete one or more payslip line items
      operationId: updatePayslip
  /Payslip/{PayslipID}:
    get:
      security:
        - OAuth2: [payroll.payslip.read]
      tags:
        - PayrollAU
      summary: searches for an payslip by unique id
      operationId: getPayslip
    post:
      security:
        - OAuth2: [payroll.payslip]
      tags:
        - PayrollAU
      summary: Update a Payslip 
      operationId: updatePayslipByID
      description:  Update lines on a single payslips
  /Settings:
    get:
      security:
        - OAuth2: [payroll.settings.read]
      tags:
        - PayrollAU
      operationId: getSettings
      summary: retrieve settings
  /Superfunds:
    get:
      security:
        - OAuth2: [payroll.superfunds.read]
      tags:
        - PayrollAU
      operationId: getSuperFunds
      summary: searches SuperFunds
    post:
      security:
        - OAuth2: [payroll.superfunds]
      tags:
        - PayrollAU
      summary: Use this method to create a super fund
      operationId: createSuperfund
  /Superfunds/{SuperFundID}:
    get:
      security:
        - OAuth2: [payroll.superfunds.read]
      tags:
        - PayrollAU
      summary: searches for an Superfund by unique id
      operationId: getSuperfund
    post:
      security:
        - OAuth2: [payroll.superfunds]
      tags:
        - PayrollAU
      summary: Update a Superfund 
      operationId: updateSuperfund
      description:  Update properties on a single Superfund
  /SuperfundProducts:
    get:
      security:
        - OAuth2: [payroll.superfundproducts.read]
      tags:
        - PayrollAU
      operationId: getSuperFundProducts
      summary: searches SuperFundProducts
  /Timesheets:
    get:
      security:
        - OAuth2: [payroll.timesheets.read]
      tags:
        - PayrollAU
      operationId: getTimesheets
      summary: searches timesheets
    post:
      security:
        - OAuth2: [payroll.timesheets]
      tags:
        - PayrollAU
      summary: Use this method to create a timesheet
      operationId: createTimesheet
  /Timesheets/{TimesheetID}:
    get:
      security:
        - OAuth2: [payroll.timesheets.read]
      tags:
        - PayrollAU
      summary: searches for an timesheet by unique id
      operationId: getTimesheet
    post:
      security:
        - OAuth2: [payroll.timesheets]
      tags:
        - PayrollAU
      summary: Update a Timesheet 
      operationId: updateTimesheet
      description:  Update properties on a single timesheet
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information visit https://developer.xero.com/documentation/oauth2/overview
      flows: 
        authorizationCode:
          authorizationUrl: 'https://login.xero.com/identity/connect/authorize'
          tokenUrl: 'https://identity.xero.com/connect/token'
          scopes:
            email: Grant read-only access to your email
            openid: Grant read-only access to your open id
            profile: your profile information
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.journals.read: Grant read-only access to journals
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.contacts: Grant read-write access to contacts and contact groups
            accounting.contacts.read: Grant read-only access to contacts and contact groups
            accounting.attachments: Grant read-write access to attachments
            accounting.attachments.read: Grant read-only access to attachments
            assets assets.read: Grant read-only access to fixed assets
            bankfeeds: Grant read-write access to bankfeeds 
            files: Grant read-write access to files and folders
            files.read: Grant read-only access to files and folders
            payroll: Grant read-write access to payroll
            payroll.read: Grant read-only access to payroll
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.leaveapplications: Grant read-write access to payroll leaveapplications
            payroll.leaveapplications.read: Grant read-only access to payroll leaveapplications
            payroll.payitems: Grant read-write access to payroll payitems
            payroll.payitems.read: Grant read-only access to payroll payitems
            payroll.payrollcalendars: Grant read-write access to payroll calendars
            payroll.payrollcalendars.read: Grant read-only access to payroll calendars
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.superfunds: Grant read-write access to payroll superfunds
            payroll.superfunds.read: Grant read-only access to payroll superfunds
            payroll.superfundproducts.read: Grant read-only access to payroll superfundproducts
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets
            paymentservices: Grant read-write access to payment services
            projects: Grant read-write access to projects
            projects.read: Grant read-only access to projects