ENABLE_LINTERS: YAML_YAMLLINT,API_SPECTRAL

APPLY_FIXES: none
FLAVOR_SUGGESTIONS: false

API_SPECTRAL_FILTER_REGEX_INCLUDE: "xero.*\\.yaml"
API_SPECTRAL_PRE_COMMANDS:
  - command: npm i @stoplight/spectral-owasp-ruleset

YAML_YAMLLINT_FILTER_REGEX_INCLUDE: "xero.*\\.yaml"
