extends: default

rules:
  line-length: disable
  trailing-spaces: disable
  indentation: disable
  colons: disable
  commas: disable
  new-line-at-end-of-file: disable
  document-start: disable
  truthy: disable
  comments: disable
  new-lines: disable