extends: default
rules:
  line-length:
    level: warning
  trailing-spaces:
    level: warning
  indentation:
    level: warning
  colons:
    level: warning
  commas:
    level: warning
  new-line-at-end-of-file:
    level: warning
