openapi: 3.0.0
info:
  version: "1.0.0"
  title: Bank Feeds API
  description: The Xero Bank Feeds API 
  contact: 
    name: Xero API team
    email: api@xero.com
  license:
    name: MIT 
    url: 'https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE'
servers:
  - description: Xero Bank Feeds API base url
    url: https://api.xero.com/bankfeeds.xro/1.0/
paths:
  /FeedConnections:
    get:
      security:
        - OAuth2: [bankfeeds]
      tags:
        - BankFeeds
      summary: searches feed connections
      operationId: getFeedConnections
      description: 
        By passing in the appropriate options, you can search for
        available feed connections in the system
      post:
        security:
          - OAuth2: [bankfeeds]
        tags:
          - BankFeeds
        summary: create one or more new feed connection
        operationId: createFeedConnections
        description: |
          By passing in the appropriate body, you can create one or more new feed connections in the system
  /FeedConnections/{id}:
    get:
      security:
        - OAuth2: [bankfeeds]
      tags:
        - BankFeeds
      summary: get single feed connection by id
      operationId: getFeedConnection
      description: |
        By passing in a FeedConnection Id options, you can search for
        available feed connections in the system
  /FeedConnections/DeleteRequests:
    post:
      security:
        - OAuth2: [bankfeeds]
      tags:
        - BankFeeds
      summary: delete an exsiting feed connection
      operationId: deleteFeedConnections
      description: |
        By passing in the appropriate body, you can create a new feed connections in the system
      security:
       - apiKey: []
  /Statements:
    get:
      security:
        - OAuth2: [bankfeeds]
      tags:
        - BankFeeds
      operationId: getStatements
    post:
      security:
        - OAuth2: [bankfeeds]
      tags:
        - BankFeeds
      operationId: createStatements
  /Statements/{statementId}:
    get:
      security:
        - OAuth2: [bankfeeds]
      tags:
        - BankFeeds
      operationId: getStatement
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information
      flows: 
        authorizationCode:
          authorizationUrl: 'https://login.xero.com/identity/connect/authorize'
          tokenUrl: 'https://identity.xero.com/connect/token'
          scopes:
            email: Grant read-only access to your email
            openid: Grant read-only access to your open id
            profile: your profile information
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.journals.read: Grant read-only access to journals
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.contacts: Grant read-write access to contacts and contact groups
            accounting.contacts.read: Grant read-only access to contacts and contact groups
            accounting.attachments: Grant read-write access to attachments
            accounting.attachments.read: Grant read-only access to attachments
            assets assets.read: Grant read-only access to fixed assets
            bankfeeds: Grant read-write access to bankfeeds 
            files: Grant read-write access to files and folders
            files.read: Grant read-only access to files and folders
            payroll: Grant read-write access to payroll
            payroll.read: Grant read-only access to payroll
            payroll.employees: Grant read-write access to payroll employees
            payroll.employees.read: Grant read-only access to payroll employees
            payroll.leaveapplications: Grant read-write access to payroll leaveapplications
            payroll.leaveapplications.read: Grant read-only access to payroll leaveapplications
            payroll.payitems: Grant read-write access to payroll payitems
            payroll.payitems.read: Grant read-only access to payroll payitems
            payroll.payrollcalendars: Grant read-write access to payroll calendars
            payroll.payrollcalendars.read: Grant read-only access to payroll calendars
            payroll.payruns: Grant read-write access to payroll payruns
            payroll.payruns.read: Grant read-only access to payroll payruns
            payroll.payslip: Grant read-write access to payroll payslips
            payroll.payslip.read: Grant read-only access to payroll payslips
            payroll.settings.read: Grant read-only access to payroll settings
            payroll.superfunds: Grant read-write access to payroll superfunds
            payroll.superfunds.read: Grant read-only access to payroll superfunds
            payroll.superfundproducts.read: Grant read-only access to payroll superfundproducts
            payroll.timesheets: Grant read-write access to payroll timesheets
            payroll.timesheets.read: Grant read-only access to payroll timesheets
            paymentservices: Grant read-write access to payment services
            projects: Grant read-write access to projects
            projects.read: Grant read-only access to projects