openapi: 3.0.0
servers:
  - url: 'https://api.xero.com/api.xro/2.0'
info:
  version: "1.0.0"
  title: Xero oAuth 2 identity service
  description: This specifing endpoints related to managing authentication tokens and identity for Xero API
  termsOfService: "https://developer.xero.com/xero-developer-platform-terms-conditions/"
  contact:
    name: "Xero Platform Team"
    email: "api@xero.com"
    url: "https://developer.xero.com"
paths:
  /connections:
    get:
      tags:
        - identity
      description: Override the base server url that include version
      operationId: getConnections
      summary: Allows you to retrieve the connections for this users
      x-basepath: 'https://api.xero.com'
  /connect/token:
    post:
      tags:
        - identity
      operationId: refreshToken
      summary: Allows you to refresh your access token
      x-basepath: 'https://identity.xero.com'
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: For more information
      flows: 
        authorizationCode:
          authorizationUrl: 'https://login.xero.com/identity/connect/authorize'
          tokenUrl: 'https://identity.xero.com/connect/token'
          scopes:
            email: Grant read-only access to your email
            openid: Grant read-only access to your open id
            profile: your profile information
            accounting.transactions: Grant read-write access to bank transactions, credit notes, invoices, repeating invoices
            accounting.transactions.read: Grant read-only access to invoices
            accounting.reports.read: Grant read-only access to accounting reports
            accounting.journals.read: Grant read-only access to journals
            accounting.settings: Grant read-write access to organisation and account settings
            accounting.settings.read: Grant read-only access to organisation and account settings
            accounting.contacts: Grant read-write access to
            accounting.contacts.read: Grant read-only access to
            accounting.attachments: Grant read-write access to
            accounting.attachments.read: Grant read-only access to
            assets assets.read: Grant read-only access to
            files: Grant read-write access to
            files.read: Grant read-only access to
            payroll: Grant read-write access to
            payroll.read: Grant read-only access to
            payroll.employees: Grant read-write access to
            payroll.employees.read: Grant read-only access to
            payroll.leaveapplications: Grant read-write access to
            payroll.leaveapplications.read: Grant read-only access to
            payroll.payitems: Grant read-write access to
            payroll.payitems.read: Grant read-only access to
            payroll.payrollcalendars: Grant read-write access to
            payroll.payrollcalendars.read: Grant read-only access to
            payroll.payruns: Grant read-write access to
            payroll.payruns.read: Grant read-only access to
            payroll.payslip: Grant read-write access to
            payroll.payslip.read: Grant read-only access to
            payroll.settings.read: Grant read-only access to
            payroll.superfunds: Grant read-write access to
            payroll.superfunds.read: Grant read-only access to
            payroll.superfundproducts.read: Grant read-only access to
            payroll.timesheets: Grant read-write access to
            payroll.timesheets.read: Grant read-only access to
            projects: Grant read-write access to projects
            projects.read: Grant read-only access to