name: Create release for Open API

on:
  workflow_dispatch:

jobs:
  OAS-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:

       - name: Checkout Repository
         uses: actions/checkout@v4

       - name: Release steps
         run: echo "this is manually triggered release....."