name: PR Validation

on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches: [master]

concurrency:
  group: codegen-validation-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  codegen-validation:
    runs-on: ubuntu-latest
    name: Codegen Repo Validation
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - name: Get github app access token
        id: get_access_token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        with:
          app-id: ${{ vars.XERO_CODEGEN_APP_ID }}
          private-key: ${{ secrets.XERO_GITHUB_APPLICATION_KEY }}
          owner: xero-internal
          repositories: xeroapi-sdk-codegen

      - name: Trigger validation workflow in codegen repo
        id: codegen_workflow
        env:
          GH_TOKEN: ${{ steps.get_access_token.outputs.token }}
          SOURCE_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
          SOURCE_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          response=$(gh api \
            --method POST \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            repos/xero-internal/xeroapi-sdk-codegen/actions/workflows/pr.yml/dispatches \
            -f ref=master \
            -F return_run_details=true \
            -f "inputs[oas_branch]=$SOURCE_SHA" \
            -f "inputs[oas_repo]=$SOURCE_REPOSITORY")

          run_id=$(jq -er '.workflow_run_id | select(type == "number")' <<< "$response")
          run_url=$(jq -er '.html_url | select(type == "string")' <<< "$response")
          echo "run_id=$run_id" >> "$GITHUB_OUTPUT"
          echo "Triggered codegen validation: $run_url"

      - name: Check status of codegen validation workflow
        env:
          GH_TOKEN: ${{ steps.get_access_token.outputs.token }}
          RUN_ID: ${{ steps.codegen_workflow.outputs.run_id }}
        run: >-
          timeout --signal=TERM 420s
          gh run watch "$RUN_ID"
          --repo xero-internal/xeroapi-sdk-codegen
          --exit-status
          --interval 5

