name: Open API PR check

on:
    pull_request:
        paths:
            - '**'

jobs:
    pr-health-check:
        runs-on: ubuntu-latest    
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'

            - name: Install yaml lint
              run: pip install yamllint

            # - name: Run yamllint
            #   run: |
            #    git fetch > /dev/null 2>&1
            #    git checkout ${{github.head_ref}}
            #    find . -type f \( -name "*.yaml" \) > yaml_files.txt

            #    if [ -s yaml_files.txt ]; then
            #     echo "linting the following yaml files:"
            #     cat yaml_files.txt
            #     xargs yamllint < yaml_files.txt
            #    fi
            
            - name: Install octokit dependencies
              run: npm i
              working-directory: ${{ github.workspace }}/.github/octokit
      
            - name: Get github app access token
              id: get_access_token
              env:
                GITHUB_APP_ID: ${{ secrets.XERO_GITHUB_APP_ID }}
                GITHUB_APP_PRIVATE_KEY: ${{ secrets.XERO_GITHUB_APPLICATION_KEY }}
              uses: actions/github-script@v7
              with:
                result-encoding: string
                script: |
                  const { getAccessToken } = await import('${{ github.workspace }}/.github/octokit/index.js')
                  const token = await getAccessToken()
                  return token

            - name: Calling node SDK workflow
              run: |
                curl --fail-with-body \
                  -XPOST \
                  -H 'Authorization: token ${{ steps.get_access_token.outputs.result }}' \
                  -H "Accept: application/vnd.github.everest-preview+json" \
                  -H "Content-Type: application/json" \
                  https://api.github.com/repos/xero-internal/xeroapi-sdk-codegen/actions/workflows/codegen-node-pr.yml/dispatches \
                  -d '{"ref":"PETOSS-536-enabling-workflow-dispatch","inputs":{"branch_name":"master"}}'